name: Deploy Website

on:
  push:
    branches: [main]
    paths:
      - "website/**"
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-website.yml
    secrets: inherit
